apiVersion: v1
kind: Pod
metadata:
  name: zap1
  labels:
    app: zap1
spec:
  containers:
    - name: zap1
      image: rtencatexebia/owasp-zap
      env: 
      - name: target #Get from vault 
        valueFrom:
          secretKeyRef:
            name: owasp-zap-secrets
            key: target
      - name: dojo-url #Get from vault 
        valueFrom:
          secretKeyRef:
            name: owasp-zap-secrets
            key: dojo-url
      - name: dojo-api-key #Get from vault 
        valueFrom:
          secretKeyRef:
            name: owasp-zap-secrets
            key: dojo-api-key
      - name: application-api-key #Get from vault 
        valueFrom:
          secretKeyRef:
            name: owasp-zap-secrets
            key: application-api-key
      - name: application-session-cookie #Get from vault 
        valueFrom:
          secretKeyRef:
            name: owasp-zap-secrets
            key: application-session-cookie
      - name: dojo-engagement-id #Get from vault 
        valueFrom:
          secretKeyRef:
            name: owasp-zap-secrets
            key: dojo-engagement-id
      command: ["zap-baseline.py"]
      args: ["-t", "$(target)", "-U", "$(dojo-url)", "-A", "$(dojo-api-key)", "-I", "$(dojo-engagement-id)", "-z", "-addoninstallall",  '"-config", "replacer.full_list(0).description=auth1", "-config", "replacer.full_list(0).enabled=true", "-config", "replacer.full_list(0).matchtype=REQ_HEADER", "-config", "replacer.full_list(0).matchstr=Authorization", "-config", "replacer.full_list(0).regex=false", "-config", "replacer.full_list(0).replacement=Bearer ", "$(application-api-key)","-config", "replacer.full_list(1).description=auth2", "-config", "replacer.full_list(1).enabled=true", "-config", "replacer.full_list(1).matchtype=REQ_HEADER", "-config", "replacer.full_list(1).matchstr=Cookie:", "-config", "replacer.full_list(1).regex=false", "-config", "replacer.full_list(1).replacement=commonAuthId=$(application-session-cookie)"']
  restartPolicy: Never
